name: Michael Paquier - Open source developer based in Japan
description: Blog about PostgreSQL and other things
url: http://michael.otacoo.com
markdown: redcarpet
pygments: true
permalink: /:categories/:title/
paginate: 10
paginate_path: page:num
